monitor.alsa.rules = [
  {
    matches = [ { device.name = "alsa_card.pci-0000_0f_00.4" } ]
    actions = {
      update-props = {
        api.acp.auto-port    = true
        api.acp.auto-profile = false
        device.profile       = "output:analog-stereo+input:analog-stereo"
      }
    }
  }
]
